"""Constants for the local knowledge indexer."""
from __future__ import annotations

from pathlib import Path

DEFAULT_ROOT = Path.cwd()
DEFAULT_STATE_DIR_NAME = "local_knowledge"

SCRIPT_SUFFIXES = {".py", ".sh", ".bash", ".cjs", ".mjs", ".js"}
EXCLUDED_DIR_NAMES = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    "__pycache__",
    "htmlcov",
    "logs",
    "node_modules",
    "venv",
    ".venv",
}
DEFAULT_KNOWN_ENTITIES = [
    "Hermes",
    "Paperless",
    "SiYuan",
    "Docker",
    "Hindsight",
    "Home Assistant",
    "Pangolin",
    "Jellyfin",
    "Vikunja",
    "Firefly",
    "LinkAce",
    "Heimdall",
    "Wazuh",
    "n8n",
    "Evolution",
    "GitHub",
    "Telegram",
    "MCP",
    "Cron",
    "Hadera",
]
STOPWORDS = {
    "about",
    "after",
    "again",
    "against",
    "agent",
    "alex",
    "and",
    "are",
    "before",
    "build",
    "can",
    "code",
    "config",
    "data",
    "default",
    "doc",
    "docs",
    "file",
    "files",
    "for",
    "from",
    "has",
    "have",
    "hermes",
    "into",
    "local",
    "markdown",
    "not",
    "note",
    "repo",
    "review",
    "run",
    "script",
    "server",
    "skill",
    "that",
    "the",
    "this",
    "tool",
    "tools",
    "use",
    "using",
    "when",
    "with",
}

QUERY_STOPWORDS = {
    "find",
    "flow",
    "markdown",
    "need",
    "next",
    "show",
    "want",
    "what",
    "where",
    "which",
}
